version: '3.8'

services:
  bot:
    build: .
    container_name: virt-council-bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: PostgreSQL database instead of SQLite
  # Uncomment to use PostgreSQL
  # db:
  #   image: postgres:16-alpine
  #   container_name: virt-council-db
  #   environment:
  #     POSTGRES_DB: virt_council
  #     POSTGRES_USER: virt_council
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
